'use client';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { brand } from '@pulsegrid/config';
import { LogoFull } from '@/components/Logo';
import { createSession } from '@/lib/api';
import { useSession } from '@/lib/session';

const highlights = [
  { title: 'Live service health', body: 'Four simulated services emit real telemetry through Redpanda; health is computed from what actually happened, never hardcoded.' },
  { title: 'Distributed traces', body: 'Every request carries W3C trace context across the whole chain. Inspect waterfalls, find the slow hop, follow the errors.' },
  { title: 'Failure simulation', body: 'Inject latency, error spikes, outages, surges, and queue stalls — then watch alerts fire, incidents open, and recovery play out.' },
  { title: 'Honest pipeline', body: 'Invalid events land in a real dead-letter queue you can retry. Alerting and root-cause hints are deterministic, not AI guesswork.' },
];

export default function LandingPage() {
  const router = useRouter();
  const { sessionId, setSession } = useSession();
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const enter = async () => {
    setError(null);
    if (sessionId) {
      router.push('/overview');
      return;
    }
    setBusy(true);
    try {
      const s = await createSession();
      setSession(s.id, s.expiresAt);
      router.push('/overview');
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setBusy(false);
    }
  };

  return (
    <main className="mx-auto flex min-h-screen max-w-4xl flex-col px-6">
      <header className="flex items-center justify-between py-6">
        <LogoFull />
        <a href={brand.repositoryUrl} target="_blank" rel="noreferrer" className="text-sm text-muted hover:text-fg">
          Source ↗
        </a>
      </header>

      <section className="flex flex-1 flex-col justify-center py-16">
        <h1 className="max-w-2xl text-4xl font-semibold leading-tight tracking-tight sm:text-5xl">
          {brand.tagline}
        </h1>
        <p className="mt-5 max-w-2xl text-lg text-muted">
          {brand.productName} is a working observability lab: an event-driven microservice chain,
          a streaming telemetry pipeline, and a control plane for breaking things on purpose —
          built to be read as much as run.
        </p>
        <div className="mt-8 flex items-center gap-4">
          <button
            onClick={enter}
            disabled={busy}
            className="rounded-md bg-accent px-5 py-2.5 text-sm font-medium text-bg transition-opacity hover:opacity-90 disabled:opacity-50"
          >
            {busy ? 'Creating your sandbox…' : sessionId ? 'Resume Live Demo' : 'Enter Live Demo'}
          </button>
          <span className="text-sm text-muted">No signup. Your session is isolated and expires after 30 minutes idle.</span>
        </div>
        {error && <p className="mt-3 text-sm text-critical">{error}</p>}
      </section>

      <section className="grid gap-4 pb-16 sm:grid-cols-2">
        {highlights.map((h) => (
          <div key={h.title} className="card p-5">
            <h2 className="text-sm font-semibold">{h.title}</h2>
            <p className="mt-1.5 text-sm leading-relaxed text-muted">{h.body}</p>
          </div>
        ))}
      </section>

      <footer className="border-t border-border py-6 text-xs text-muted">
        All traffic, incidents, and failures here are synthetic and generated by {brand.productName} itself.
      </footer>
    </main>
  );
}
