/**
 * Central brand configuration. Every user-visible product string, color token,
 * and external URL lives here so rebranding is a one-file change.
 */
export const brand = {
  productName: 'PulseGrid',
  tagline: 'Real-time visibility into distributed systems.',
  logoText: 'PulseGrid',
  metaDescription:
    'PulseGrid is a real-time distributed-systems observability laboratory: live service health, distributed traces, alerting, incidents, and failure simulation on a functioning event-driven pipeline.',
  repositoryUrl: 'https://github.com/vanessagomezmcc/pulsegrid.git',
  liveUrl: 'https://pulsegrid.example.com',
  demoBanner: "Live synthetic telemetry generated by PulseGrid's simulated services.",
} as const;

export const navigation = [
  { label: 'Overview', href: '/overview' },
  { label: 'Services', href: '/services' },
  { label: 'Traces', href: '/traces' },
  { label: 'Alerts', href: '/alerts' },
  { label: 'Incidents', href: '/incidents' },
  { label: 'Event Stream', href: '/events' },
  { label: 'Dead-Letter Queue', href: '/dead-letter' },
  { label: 'Simulation Lab', href: '/lab' },
  { label: 'Architecture', href: '/architecture' },
  { label: 'About', href: '/about' },
] as const;

/** Design tokens are mirrored as CSS variables in apps/web/src/app/globals.css. */
export const colors = {
  bg: '#0b0f17',
  bgSecondary: '#111827',
  surface: '#161e2e',
  border: '#2a3648',
  text: '#e6eaf2',
  textMuted: '#8b98ad',
  accent: '#38bdf8',
  healthy: '#34d399',
  warning: '#fbbf24',
  critical: '#f87171',
  unknown: '#6b7280',
} as const;
